name: GhostMansion
version: 1.0
main: com.ohmast.ghost.Plugin
commands:
  start:
    description: Starts the game.
  test:
    description: Test
  spawnb:
    description: Spawns a battery.
  st:
    description: stops game
  cl:
    description: clears stats